name: 游 Deploy Nuxt

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Checkout c칩digo fuente
        uses: actions/checkout@v4

      - name: 游 Instalar dependencias
        run: npm install

      - name: 游끵 Build Nuxt
        run: npm run build

      - name: 游 Deploy a repo de producci칩n
        run: |
          cd .output/public   # 丘멆잺 si usas Nuxt 3, aqu칤 est치 tu build
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy desde Actions 游"
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/usuario/repo-deploy.git
          git push -f origin main
